package com.model;

public abstract class DataConstants {
  public static final String USER_FILE_LOCATION = "src/main/java/com/data/users.json";
  public static final String USER_OBJECT_KEY = "users";
  public static final String USER_ID = "id";
  public static final String USER_EMAIL = "email";
  public static final String USER_USERNAME = "username";
  public static final String USER_PASSWORD = "password";
  public static final String USER_FAVORITED_SONGS = "favoriteSongs";
  public static final String USER_FOLLOWED_USERS = "followedUsers";
  public static final String USER_THEME_COLOR = "themeColor";

  public static final String SONG_FILE_LOCATION = "src/main/java/com/data/songs.json";
  public static final String SONG_OBJECT_KEY = "songs";
  public static final String SONG_ID = "id";
  public static final String SONG_TITLE = "title";
  public static final String SONG_COMPOSER = "composer";
  public static final String SONG_PUBLISHER = "publisher";
  public static final String SONG_PICK_UP = "pickUp";
  public static final String SONG_SHEET_MUSIC = "sheetMusic";
  public static final String SONG_INSTRUMENT = "instrument";
  public static final String SONG_INSTRUMENT_NAME = "instrumentName";
  public static final String SONG_INSTRUMENT_CLEF_TYPES = "clefTypes";
  public static final String SONG_STAVES = "staves";
  public static final String SONG_STAFF_CLEF_TYPE = "clefType";
  public static final String SONG_MEASURES = "measures";
  public static final String SONG_MEASURES_KEY_SIGNATURE = "keySignature";
  public static final String SONG_MEASURES_TIME_SIGNATURE_NUMERATOR = "timeSignatureNumerator";
  public static final String SONG_MEASURES_TIME_SIGNATURE_DENOMINATOR = "timeSignatureDenominator";
  public static final String SONG_MEASURES_TEMPO = "tempo";
  public static final String SONG_MUSIC_ELEMENTS = "musicElements";
  public static final String SONG_MUSIC_ELEMENT_REST = "rest";
  public static final String SONG_MUSIC_ELEMENT_TUPLET = "tuplet";
  public static final String SONG_MUSIC_ELEMENT_NOTE = "note";
  public static final String SONG_MUSIC_ELEMENT_CHORD = "chord";
  public static final String SONG_MUSIC_ELEMENT_TYPE = "type";
  public static final String SONG_MUSIC_ELEMENT_PITCH = "pitch";
  public static final String SONG_MUSIC_ELEMENT_MIDI_NUMBER = "midiNumber";
  public static final String SONG_MUSIC_ELEMENT_NOTE_NAME = "noteName";
  public static final String SONG_MUSIC_ELEMENT_DURATION = "duration";
  public static final String SONG_MUSIC_ELEMENT_DURATION_CHAR = "durationChar";
  public static final String SONG_MUSIC_ELEMENT_DOTTED = "dotted";
  public static final String SONG_MUSIC_ELEMENT_TIED = "tied";
  public static final String SONG_MUSIC_ELEMENT_LYRIC = "lyric";
  public static final String SONG_MUSIC_ELEMENT_SUBDIVISIONS = "subdivisions";
  public static final String SONG_MUSIC_ELEMENT_IMPLIED_DIVISION = "impliedDivision";
  public static final String SONG_MUSIC_ELEMENT_TUPLET_ELEMENTS = "elements";
  public static final String SONG_MUSIC_ELEMENT_CHORD_NOTES = "notes";
}
